In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('data/AB_NYC_2019.csv')

In [2]:
X_train1 = pd.DataFrame(df['neighbourhood_group'])

enc = OneHotEncoder(sparse=False, handle_unknown='ignore')
X_train1_ohe = enc.fit_transform(X_train1)
print(X_train1_ohe[:10])

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [3]:
X_train2 = pd.DataFrame(df['room_type'])

enc = OrdinalEncoder(categories = [['Entire home/apt','Private room', 'Shared room']]) 
X_train2_oe = enc.fit_transform(X_train2)

print(X_train2_oe[:10])

[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]]


In [4]:
X_train3 = pd.DataFrame(df['number_of_reviews'])

scaler = StandardScaler()
X_train3_ss = scaler.fit_transform(X_train3)

print(X_train3_ss[:10])

[[-0.32041358]
 [ 0.48766493]
 [-0.52243321]
 [ 5.53815562]
 [-0.32041358]
 [ 1.13861706]
 [ 0.57745143]
 [ 9.12961566]
 [ 2.12626857]
 [ 3.06902683]]


In [5]:
X_train4 = pd.DataFrame(df['reviews_per_month'])

scaler = StandardScaler()
X_train4_ss = scaler.fit_transform(X_train4)

print(X_train4_ss[:10])

[[-0.6922205 ]
 [-0.59105534]
 [        nan]
 [ 1.94402463]
 [-0.75768031]
 [-0.46608661]
 [-0.57915356]
 [ 1.24777027]
 [-0.22805093]
 [-0.02572061]]


In [6]:
X_train5 = pd.DataFrame(df['availability_365'])

scaler = MinMaxScaler()
X_train5_mm = scaler.fit_transform(X_train5)

print(X_train5_mm[:10])

[[1.        ]
 [0.97260274]
 [1.        ]
 [0.53150685]
 [0.        ]
 [0.35342466]
 [0.        ]
 [0.60273973]
 [0.        ]
 [0.51506849]]


In [7]:
res = np.concatenate((X_train1_ohe,X_train2_oe, X_train3_ss, X_train4_ss,X_train5_mm),axis=1)
df = pd.DataFrame(data=res)
print(df[:10])

     0    1    2    3    4    5         6         7         8
0  0.0  1.0  0.0  0.0  0.0  1.0 -0.320414 -0.692221  1.000000
1  0.0  0.0  1.0  0.0  0.0  0.0  0.487665 -0.591055  0.972603
2  0.0  0.0  1.0  0.0  0.0  1.0 -0.522433       NaN  1.000000
3  0.0  1.0  0.0  0.0  0.0  0.0  5.538156  1.944025  0.531507
4  0.0  0.0  1.0  0.0  0.0  0.0 -0.320414 -0.757680  0.000000
5  0.0  0.0  1.0  0.0  0.0  0.0  1.138617 -0.466087  0.353425
6  0.0  1.0  0.0  0.0  0.0  1.0  0.577451 -0.579154  0.000000
7  0.0  0.0  1.0  0.0  0.0  1.0  9.129616  1.247770  0.602740
8  0.0  0.0  1.0  0.0  0.0  1.0  2.126269 -0.228051  0.000000
9  0.0  0.0  1.0  0.0  0.0  0.0  3.069027 -0.025721  0.515068
